spring:
  application:
    name: consumer
  cloud:
    consul:
      host: localhost
      port: 8500

server:
  port: 8080

#eureka:
#  server:
#    host: localhost:8761
#    contextPath: registry
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://${eureka.server.host}/${eureka.server.contextPath}/eureka}
#  instance:
#    preferIpAddress: true